### ISSUE TITLE
FIGMA TASK

### ISSUE THREAD

**Issue by markjordanugtongspc** [markjordanugtongspc/spc-qr-code-attendance#56]
**A To Do List in Figma;**

Di kaayo sha importanti pero, ato lng daanan ug importansha, bali goods pud ni sha aron naa tay ma sun-an sa coding, bali eh redesign lng sha then naa koy list sa mga todo diari nga pwede ramo mamili unsa inyo buhaton then provide lng ug screenshot if nahuman nimo then eh comment lng dayon dre aron ma track nako ang mga nahumana na.

**TO DO FIGMA;**
- Create Branding and color pallete and font list on figma
- Gate Pass [Remove Button, then replace icon to actual camera]
- Signin/Signup [Change Font Color, re-arrange based on current views login]
- Parents Dashboard [Rebased to views/menu should be refix to original not in template]
- Student Dashboard [same on parents dashboard task] 

@Kocorbs @christianmaglangit @markjordanugtongspc @sherie01 @cathyang2,

**Comment by sherie01** [comment]
![Image](https://github.com/markjordanugtongspc/spc-qr-code-attendance/assets/159250295/d639b3c0-a67d-4740-8bf8-80dd17a2705a)

**Comment by markjordanugtongspc** [comment]
All Task Finish by @sherie01

**Comment by sherie01** [comment]
![Image](https://github.com/markjordanugtongspc/spc-qr-code-attendance/assets/159250295/5a404e15-cea0-48d1-8e12-319621d4d53e)

**Comment by sherie01** [comment]
![Image](https://github.com/markjordanugtongspc/spc-qr-code-attendance/assets/159250295/e267eb9d-9f8c-4de6-a3c8-deaf522645c8)

**Comment by sherie01** [comment]
![Image](https://github.com/markjordanugtongspc/spc-qr-code-attendance/assets/159250295/1ad58744-5dde-4456-9b01-41a9f801d21f)

**Comment by sherie01** [comment]
![Image](https://github.com/markjordanugtongspc/spc-qr-code-attendance/assets/159250295/319d0d8b-19f5-43a9-b828-9d6f6950c6d2)

**Comment by sherie01** [comment]
![Image](https://github.com/markjordanugtongspc/spc-qr-code-attendance/assets/159250295/8c13244a-7fbc-46f6-b848-b8bb2d592272)

**Comment by sherie01** [comment]
![Image](https://github.com/markjordanugtongspc/spc-qr-code-attendance/assets/159250295/b81e3ac2-aade-4448-819a-d179ef42f44b)
